version: '3.8'

services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: calculator-orchestrator
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=${PORT:-8080}
    volumes:
      - ./logs:/app/logs
      - ./web:/app/web
    networks:
      - calculator-network

  agent:
    build:
      context: .
      dockerfile: Dockerfile2
    environment:
      - COMPUTING_POWER=${COMPUTING_POWER:-4}
      - TIME_ADDITION_MS=${TIME_ADDITION_MS:-1000}
      - TIME_SUBTRACTION_MS=${TIME_SUBTRACTION_MS:-1000}
      - TIME_MULTIPLICATIONS_MS=${TIME_MULTIPLICATIONS_MS:-2000}
      - TIME_DIVISIONS_MS=${TIME_DIVISIONS_MS:-2000}
      - ORCHESTRATOR_URL=http://orchestrator:8080
    depends_on:
      - orchestrator
    volumes:
      - ./logs:/app/logs
    networks:
      - calculator-network

networks:
  calculator-network:
    driver: bridge