services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/orchestrator"]
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "50051:50051"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:50051"]
      interval: 2s
      timeout: 2s
      retries: 10

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/agent"]
    depends_on:
      - orchestrator
    env_file:
      - .env
