// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: api/orchestrator.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_orchestrator_proto protoreflect.FileDescriptor

const file_api_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x16api/orchestrator.proto\x12\x18github.com.structxz.calc\x1a\x12api/messages.proto2\xca\x01\n" +
	"\fOrchestrator\x12V\n" +
	"\aGetTask\x12#.github.com.structxz.calc.AgentInfo\x1a&.github.com.structxz.calc.TaskResponse\x12b\n" +
	"\x10SubmitTaskResult\x12$.github.com.structxz.calc.TaskResult\x1a(.github.com.structxz.calc.SubmitResponseB%Z#github.com/structxz/calc_v3/api;apib\x06proto3"

var file_api_orchestrator_proto_goTypes = []any{
	(*AgentInfo)(nil),      // 0: github.com.structxz.calc.AgentInfo
	(*TaskResult)(nil),     // 1: github.com.structxz.calc.TaskResult
	(*TaskResponse)(nil),   // 2: github.com.structxz.calc.TaskResponse
	(*SubmitResponse)(nil), // 3: github.com.structxz.calc.SubmitResponse
}
var file_api_orchestrator_proto_depIdxs = []int32{
	0, // 0: github.com.structxz.calc.Orchestrator.GetTask:input_type -> github.com.structxz.calc.AgentInfo
	1, // 1: github.com.structxz.calc.Orchestrator.SubmitTaskResult:input_type -> github.com.structxz.calc.TaskResult
	2, // 2: github.com.structxz.calc.Orchestrator.GetTask:output_type -> github.com.structxz.calc.TaskResponse
	3, // 3: github.com.structxz.calc.Orchestrator.SubmitTaskResult:output_type -> github.com.structxz.calc.SubmitResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_orchestrator_proto_init() }
func file_api_orchestrator_proto_init() {
	if File_api_orchestrator_proto != nil {
		return
	}
	file_api_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orchestrator_proto_rawDesc), len(file_api_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_orchestrator_proto_goTypes,
		DependencyIndexes: file_api_orchestrator_proto_depIdxs,
	}.Build()
	File_api_orchestrator_proto = out.File
	file_api_orchestrator_proto_goTypes = nil
	file_api_orchestrator_proto_depIdxs = nil
}
